version: '3'

services:
  gogs:
    image: gogs/gogs
    ports:
      - '10022:22'
      - '3000:3000'
    volumes:
      - './gogs:/data'

  teamcity-server:
    image: 'jetbrains/teamcity-server'
    volumes:
      - './teamcity/data:/data/teamcity_server/datadir'
      - './teamcity/log:/data/teamcity/logs'
    ports:
      - '8111:8111'
    environment:
      - TEAMCITY_SERVER_MEM_OPTS="-Xmx750m"
    links:
      - gogs
      - teamcity-agent
    
  teamcity-agent:
    image: 'jetbrains/teamcity-agent'
    environment:
      - SERVER_URL=teamcity-server:8111
    links:
      - gogs

  spring-initializr:
    image: ssherwood/initializr
    ports:
      - '8081:8080'
    volumes:
      - '/tmp'