resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: pivotalpa/cf-cli-resource
    tag: latest

resources:
- name: git-repo
  type: git
  source:
    uri: http://gogs:3000/gogs/first.git
    branch: master
- name: cf-env
  type: cf-cli-resource
  source:
    api: https://api.system.com
    username: staff
    password: staff
    skip_cert_check: true

jobs:
- name: package
  plan:
  - get: git-repo
    trigger: true
  - task: mvn-package
    privileged: true
    file: git-repo/ci/mvn-package.yml
  - put: cf-push
    resource: cf-env
    params:
      command: push
      app_name: shawn-app
      hostname: shawn-app
      memory: 1G
      disk_quota: 1G
      instances: 1
      path: git-repo/target/demo-*.jar
      buildpack: java_buildpack
      manifest: git-repo/manifest.yml
      no_start: true
